package com.photoshareweb.entitys;

import java.util.Date;

public class Photo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.photourl
     *
     * @mbggenerated
     */
    private String photourl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.photoname
     *
     * @mbggenerated
     */
    private String photoname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.photoclass
     *
     * @mbggenerated
     */
    private Integer photoclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.descriptions
     *
     * @mbggenerated
     */
    private String descriptions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.uploadtime
     *
     * @mbggenerated
     */
    private Date uploadtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.uploaduser
     *
     * @mbggenerated
     */
    private String uploaduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.id
     *
     * @return the value of photo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.id
     *
     * @param id the value for photo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.photourl
     *
     * @return the value of photo.photourl
     *
     * @mbggenerated
     */
    public String getPhotourl() {
        return photourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.photourl
     *
     * @param photourl the value for photo.photourl
     *
     * @mbggenerated
     */
    public void setPhotourl(String photourl) {
        this.photourl = photourl == null ? null : photourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.photoname
     *
     * @return the value of photo.photoname
     *
     * @mbggenerated
     */
    public String getPhotoname() {
        return photoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.photoname
     *
     * @param photoname the value for photo.photoname
     *
     * @mbggenerated
     */
    public void setPhotoname(String photoname) {
        this.photoname = photoname == null ? null : photoname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.photoclass
     *
     * @return the value of photo.photoclass
     *
     * @mbggenerated
     */
    public Integer getPhotoclass() {
        return photoclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.photoclass
     *
     * @param photoclass the value for photo.photoclass
     *
     * @mbggenerated
     */
    public void setPhotoclass(Integer photoclass) {
        this.photoclass = photoclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.descriptions
     *
     * @return the value of photo.descriptions
     *
     * @mbggenerated
     */
    public String getDescriptions() {
        return descriptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.descriptions
     *
     * @param descriptions the value for photo.descriptions
     *
     * @mbggenerated
     */
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions == null ? null : descriptions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.uploadtime
     *
     * @return the value of photo.uploadtime
     *
     * @mbggenerated
     */
    public Date getUploadtime() {
        return uploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.uploadtime
     *
     * @param uploadtime the value for photo.uploadtime
     *
     * @mbggenerated
     */
    public void setUploadtime(Date uploadtime) {
        this.uploadtime = uploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.uploaduser
     *
     * @return the value of photo.uploaduser
     *
     * @mbggenerated
     */
    public String getUploaduser() {
        return uploaduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.uploaduser
     *
     * @param uploaduser the value for photo.uploaduser
     *
     * @mbggenerated
     */
    public void setUploaduser(String uploaduser) {
        this.uploaduser = uploaduser == null ? null : uploaduser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.status
     *
     * @return the value of photo.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.status
     *
     * @param status the value for photo.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}