package com.photoshareweb.entitys;

public class PhotoClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photoclass.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photoclass.classname
     *
     * @mbggenerated
     */
    private String classname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photoclass.id
     *
     * @return the value of photoclass.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photoclass.id
     *
     * @param id the value for photoclass.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photoclass.classname
     *
     * @return the value of photoclass.classname
     *
     * @mbggenerated
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photoclass.classname
     *
     * @param classname the value for photoclass.classname
     *
     * @mbggenerated
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }
}