package com.photoshareweb.dao;

import com.photoshareweb.entitys.PhotoClass;

public interface PhotoClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photoclass
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photoclass
     *
     * @mbggenerated
     */
    int insert(PhotoClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photoclass
     *
     * @mbggenerated
     */
    int insertSelective(PhotoClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photoclass
     *
     * @mbggenerated
     */
    PhotoClass selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photoclass
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PhotoClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photoclass
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PhotoClass record);
}