package com.photoshareweb.dao;

import com.photoshareweb.entitys.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    User hasAccount(User record);

    User getSimpleUserByAccount(User record);

    User getUserByAccount(User record);

    int updateUser(User user);

    int changePassword(User user);
}